baseURL: "https://sh4x2.dev/"
title: sh4x2
theme: PaperMod

params:
  homeInfoParams:
    Title: Hi!

  socialIcons:
    - name: github
      url: "https://github.com/sh4x2"

  assets:
    favicon: "/assets/favicon.ico"
